import React, { ReactNode } from 'react'
import Head from "next/head"

import styles from './Layout.module.scss'
import Link from 'next/link'

interface LayoutProps {
  children: ReactNode
}

interface MenuItem {
  name: string
  linkTo: string
}

type MenuItems = MenuItem[]

const menuItems: MenuItems = [
  { name: "Home", linkTo: "/" },
  { name: "Events", linkTo: "/events" },
  { name: "Users", linkTo: "/users" },
]

const Layout = ({ children }: LayoutProps) => (
  <div className={styles.pageWrapper}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header className={styles.header}>
      <div className={styles.container}></div>
    </header>

    <div className={styles.main}>
      <nav className={styles.navBar}>
        <ul>
          <li>Home</li>
          <li>News</li>
          <li>Events</li>
          <li>Users</li>
        </ul>
      </nav>
      <section className={styles.center}></section>
      <section className={styles.right}></section>
    </div>

    <footer className={styles.footer}>
      <section className={styles.container}></section>
    </footer>
  </div>
);

export default Layout

