import React, { ReactNode } from 'react'
import Head from "next/head";

import styles from './Layout.module.css'

interface LayoutProps {
    children: ReactNode
}

const Header = () => (
    <header className={styles.header}>

    </header>
)

const Nav = () => (
    <div></div>
)

const Footer = () => (
    <footer></footer>
)

const Layout  = ({ children }: LayoutProps) => {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />

        <main>
          <Nav></Nav>
          <div>{children}</div>
        </main>
        <Footer />
      </div>
    );
}

export default Layout

