import React, { ReactNode } from 'react'
import Head from "next/head"

import styles from './Layout.module.scss'
import Link from 'next/link'

interface LayoutProps {
  children: ReactNode
}

interface MenuItem {
  name: string
  linkTo: string
}

type MenuItems = MenuItem[]

const menuItems: MenuItems = [
  { name: "Home", linkTo: "/" },
  { name: "Events", linkTo: "/events" },
  { name: "Users", linkTo: "/users" },
]

const Layout  = ({ children }: LayoutProps) => {
    return (
      <div className={styles.pageWrapper}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.header}></header>

        <div className={styles.container}>
          <div className={styles.left}>
            <div className={styles.nav}>
              <ul>
                {menuItems.map(({ name, linkTo }) => (
                  <Link key={`nav-${name}`} href={linkTo}><li>{name}</li></Link>
                ))}
              </ul>
            </div>
          </div>
          <main className={styles.main}>{children}</main>
          <div className={styles.right}></div>
        </div>

        <footer className={styles.footer}></footer>
      </div>
    )
}

export default Layout

